package vistas;

import javax.swing.ImageIcon;

public class BuscarCliente extends javax.swing.JFrame {

    public BuscarCliente() {
        initComponents();
        this.setTitle("Buscar cliente");
        //ICONO
        setIconImage(new ImageIcon(getClass().getResource("/imgs/MercadoAbasto_icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jlusuario = new javax.swing.JLabel();
        tffechaactual = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        tfdireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jbbuscar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        tfcliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfcuit = new javax.swing.JTextField();
        jbnuevocliente = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tflectura = new javax.swing.JTextField();
        jbcancelar = new javax.swing.JButton();
        jbaceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 4, 55));

        jlusuario.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jlusuario.setForeground(new java.awt.Color(153, 153, 153));
        jlusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/user.png"))); // NOI18N
        jlusuario.setText("Usuario: MAJO_ADM");
        jlusuario.setFocusable(false);
        jPanel2.add(jlusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        tffechaactual.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        tffechaactual.setForeground(new java.awt.Color(153, 153, 153));
        tffechaactual.setText("Fecha actual: 25/7/2018");
        tffechaactual.setBorder(null);
        tffechaactual.setFocusable(false);
        tffechaactual.setOpaque(false);
        jPanel2.add(tffechaactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 68, -1, -1));

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/calendar.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 132));

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 205, 220, 1));

        tfdireccion.setFont(new java.awt.Font("Open Sans Light", 0, 17)); // NOI18N
        tfdireccion.setForeground(new java.awt.Color(153, 153, 153));
        tfdireccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfdireccion.setText("Verdulandia SRL");
        tfdireccion.setBorder(null);
        tfdireccion.setOpaque(false);
        jPanel1.add(tfdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 225, 390, -1));

        jLabel4.setFont(new java.awt.Font("Open Sans Light", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cliente.png"))); // NOI18N
        jLabel4.setText("Nombre / Razón social del cliente:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jTextField2.setBackground(new java.awt.Color(2, 166, 57));
        jTextField2.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("BUSCAR CLIENTE");
        jTextField2.setBorder(null);
        jTextField2.setFocusable(false);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, -1));

        jbbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/buscar_off.png"))); // NOI18N
        jbbuscar.setBorder(null);
        jbbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbbuscar.setOpaque(false);
        jbbuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/buscar_on.png"))); // NOI18N
        jbbuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/buscar_on.png"))); // NOI18N
        jbbuscar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/buscar_on.png"))); // NOI18N
        jPanel1.add(jbbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 185, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 1, 58));

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/point.png"))); // NOI18N
        jLabel5.setText("Dirección:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 225, -1, -1));

        tfcliente.setFont(new java.awt.Font("Open Sans Light", 0, 17)); // NOI18N
        tfcliente.setForeground(new java.awt.Color(153, 153, 153));
        tfcliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfcliente.setText("Verdulandia SRL");
        tfcliente.setBorder(null);
        tfcliente.setOpaque(false);
        jPanel1.add(tfcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 220, -1));

        jLabel6.setFont(new java.awt.Font("Open Sans", 0, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cuit.png"))); // NOI18N
        jLabel6.setText("CUIT:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        tfcuit.setFont(new java.awt.Font("Open Sans Light", 0, 17)); // NOI18N
        tfcuit.setForeground(new java.awt.Color(153, 153, 153));
        tfcuit.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfcuit.setText("40-12456789-7");
        tfcuit.setBorder(null);
        tfcuit.setOpaque(false);
        jPanel1.add(tfcuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 420, -1));

        jbnuevocliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/nuevo_cliente_off.png"))); // NOI18N
        jbnuevocliente.setBorder(null);
        jbnuevocliente.setOpaque(false);
        jbnuevocliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/nuevo_cliente_on.png"))); // NOI18N
        jbnuevocliente.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/nuevo_cliente_on.png"))); // NOI18N
        jbnuevocliente.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/nuevo_cliente_on.png"))); // NOI18N
        jPanel1.add(jbnuevocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jTextField6.setBackground(new java.awt.Color(2, 166, 57));
        jTextField6.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("PUESTO:");
        jTextField6.setBorder(null);
        jTextField6.setFocusable(false);
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 335, 90, -1));

        jLabel7.setFont(new java.awt.Font("Open Sans", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/kw.png"))); // NOI18N
        jLabel7.setText("Última lectura medidor:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 333, -1, -1));

        tflectura.setFont(new java.awt.Font("Open Sans Light", 0, 17)); // NOI18N
        tflectura.setForeground(new java.awt.Color(153, 153, 153));
        tflectura.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tflectura.setText("56 Kw.");
        tflectura.setBorder(null);
        tflectura.setOpaque(false);
        jPanel1.add(tflectura, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 333, 180, -1));

        jbcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cancelar_off.png"))); // NOI18N
        jbcancelar.setBorder(null);
        jbcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcancelar.setOpaque(false);
        jbcancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cancelar_on.png"))); // NOI18N
        jbcancelar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cancelar_on.png"))); // NOI18N
        jbcancelar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cancelar_on.png"))); // NOI18N
        jPanel1.add(jbcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, -1));

        jbaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/aceptar_off.png"))); // NOI18N
        jbaceptar.setBorder(null);
        jbaceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbaceptar.setOpaque(false);
        jbaceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/aceptar_on.png"))); // NOI18N
        jbaceptar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/aceptar_on.png"))); // NOI18N
        jbaceptar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/aceptar_on.png"))); // NOI18N
        jPanel1.add(jbaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton jbaceptar;
    private javax.swing.JButton jbbuscar;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JButton jbnuevocliente;
    private javax.swing.JLabel jlusuario;
    private javax.swing.JTextField tfcliente;
    private javax.swing.JTextField tfcuit;
    private javax.swing.JTextField tfdireccion;
    private javax.swing.JTextField tffechaactual;
    private javax.swing.JTextField tflectura;
    // End of variables declaration//GEN-END:variables
}
