package vistas;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.table.JTableHeader;

public class RegistroAlquilerPuesto extends javax.swing.JFrame {

    public RegistroAlquilerPuesto() {
        initComponents();
        this.setTitle("Registro alquiler puesto");
        //ICONO
        setIconImage(new ImageIcon(getClass().getResource("/imgs/MercadoAbasto_icon.png")).getImage());
        //DISEÑO TABLAS
        JTableHeader encabezado = tabla.getTableHeader();
        encabezado.setForeground(Color.white);
        encabezado.setBackground(new Color(245,104,46));
        encabezado.setFont(new Font("Open Sans", Font.BOLD, 15));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlusuario = new javax.swing.JLabel();
        tffechaactual = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tffechainicio = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        tffechavencimiento = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbtipopuesto = new javax.swing.JComboBox<>();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        cbdimension = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jbcancelar = new javax.swing.JButton();
        jbaceptar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(237, 237, 237));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 4, 55));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/calendar.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jlusuario.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jlusuario.setForeground(new java.awt.Color(153, 153, 153));
        jlusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/user.png"))); // NOI18N
        jlusuario.setText("Usuario: MAJO_ADM");
        jlusuario.setFocusable(false);
        jPanel2.add(jlusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        tffechaactual.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        tffechaactual.setForeground(new java.awt.Color(153, 153, 153));
        tffechaactual.setText("Fecha actual: 25/7/2018");
        tffechaactual.setBorder(null);
        tffechaactual.setFocusable(false);
        tffechaactual.setOpaque(false);
        jPanel2.add(tffechaactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 68, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 132));

        jTextField2.setBackground(new java.awt.Color(2, 166, 57));
        jTextField2.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("SELECCIONE PERÍODO");
        jTextField2.setBorder(null);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, -1));

        jLabel4.setFont(new java.awt.Font("Open Sans Light", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/fechas.png"))); // NOI18N
        jLabel4.setText("Fecha inicio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        tffechainicio.setFont(new java.awt.Font("Open Sans Light", 0, 17)); // NOI18N
        tffechainicio.setForeground(new java.awt.Color(153, 153, 153));
        tffechainicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tffechainicio.setText("25/7/2018");
        tffechainicio.setBorder(null);
        tffechainicio.setOpaque(false);
        jPanel1.add(tffechainicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 180, 100, -1));

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 205, 95, 1));

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 178, 1, 34));

        jLabel5.setFont(new java.awt.Font("Open Sans Light", 0, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/fechas.png"))); // NOI18N
        jLabel5.setText("Fecha vencimiento:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        tffechavencimiento.setFont(new java.awt.Font("Open Sans Light", 0, 17)); // NOI18N
        tffechavencimiento.setForeground(new java.awt.Color(153, 153, 153));
        tffechavencimiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tffechavencimiento.setText("25/7/2018");
        tffechavencimiento.setBorder(null);
        tffechavencimiento.setOpaque(false);
        jPanel1.add(tffechavencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 100, -1));

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 205, 95, 1));

        jTextField5.setBackground(new java.awt.Color(2, 166, 57));
        jTextField5.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("SELECCIONE CARACTERÍSTICAS DEL PUESTO");
        jTextField5.setBorder(null);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 340, -1));

        jLabel6.setFont(new java.awt.Font("Open Sans Light", 0, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/puesto.png"))); // NOI18N
        jLabel6.setText("Tipo de puesto:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        cbtipopuesto.setFont(new java.awt.Font("Open Sans Light", 0, 17)); // NOI18N
        cbtipopuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbtipopuesto.setBorder(null);
        cbtipopuesto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbtipopuesto.setOpaque(false);
        jPanel1.add(cbtipopuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 120, -1));

        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 1, 34));

        jLabel7.setFont(new java.awt.Font("Open Sans Light", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/size.png"))); // NOI18N
        jLabel7.setText("Dimensión:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        cbdimension.setFont(new java.awt.Font("Open Sans Light", 0, 17)); // NOI18N
        cbdimension.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbdimension.setBorder(null);
        cbdimension.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbdimension.setOpaque(false);
        jPanel1.add(cbdimension, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 120, -1));

        jTextField6.setBackground(new java.awt.Color(2, 166, 57));
        jTextField6.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("SELECCIONE CARACTERÍSTICAS DEL PUESTO");
        jTextField6.setBorder(null);
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 340, -1));

        tabla.setFont(new java.awt.Font("Open Sans Light", 0, 15)); // NOI18N
        tabla.setForeground(new java.awt.Color(153, 153, 153));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "Ala Sur", "15", "10", "$450"},
                {null, "Ala Sur", "8", "10", "$350"},
                {null, "Ala Norte", "52", "10", "$600"},
                {null, "Ala Este", "11", "10", "$120"}
            },
            new String [] {
                "", "SECTOR", "NÚMERO", "DIMENSIONES", "ALQUILER"
            }
        ));
        tabla.setGridColor(new java.awt.Color(255, 255, 255));
        tabla.setRowHeight(21);
        tabla.setSelectionBackground(new java.awt.Color(240, 240, 240));
        jScrollPane2.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(2).setResizable(false);
            tabla.getColumnModel().getColumn(3).setResizable(false);
            tabla.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 580, 110));

        jbcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cancelar_off.png"))); // NOI18N
        jbcancelar.setBorder(null);
        jbcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcancelar.setOpaque(false);
        jbcancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cancelar_on.png"))); // NOI18N
        jbcancelar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cancelar_on.png"))); // NOI18N
        jbcancelar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cancelar_on.png"))); // NOI18N
        jPanel1.add(jbcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, -1, -1));

        jbaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/aceptar_off.png"))); // NOI18N
        jbaceptar.setBorder(null);
        jbaceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbaceptar.setOpaque(false);
        jbaceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/aceptar_on.png"))); // NOI18N
        jbaceptar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/aceptar_on.png"))); // NOI18N
        jbaceptar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/aceptar_on.png"))); // NOI18N
        jPanel1.add(jbaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAlquilerPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAlquilerPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAlquilerPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAlquilerPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAlquilerPuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbdimension;
    private javax.swing.JComboBox<String> cbtipopuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton jbaceptar;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JLabel jlusuario;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField tffechaactual;
    private javax.swing.JTextField tffechainicio;
    private javax.swing.JTextField tffechavencimiento;
    // End of variables declaration//GEN-END:variables
}
